"""Create Candicade Table


Revision ID: D0001
Revises: 
Create Date: 2023-11-28 10:57:56.341596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision: str = 'D0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidate_education',
    sa.Column('id', sa.SMALLINT(), nullable=False),
    sa.Column('candidate_id', sa.SMALLINT(), nullable=False),
    sa.Column('school', sa.NVARCHAR(length=50), nullable=False),
    sa.Column('major', sa.NVARCHAR(length=50), nullable=False),
    sa.Column('description', sa.NVARCHAR(length=100), nullable=True),
    sa.Column('start_date', mssql.DATETIMEOFFSET(), nullable=False),
    sa.Column('end_date', mssql.DATETIMEOFFSET(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('candidate_experience',
    sa.Column('id', sa.SMALLINT(), nullable=False),
    sa.Column('candidate_id', sa.SMALLINT(), nullable=False),
    sa.Column('company', sa.NVARCHAR(length=50), nullable=False),
    sa.Column('position', sa.NVARCHAR(length=50), nullable=False),
    sa.Column('description', sa.NVARCHAR(length=100), nullable=True),
    sa.Column('start_date', mssql.DATETIMEOFFSET(), nullable=False),
    sa.Column('end_date', mssql.DATETIMEOFFSET(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('candidate_info',
    sa.Column('id', sa.SMALLINT(), nullable=False),
    sa.Column('name', sa.NVARCHAR(length=50), nullable=False),
    sa.Column('email', sa.VARCHAR(length=50), nullable=False),
    sa.Column('phone', sa.CHAR(length=10), nullable=False),
    sa.Column('address', sa.NVARCHAR(length=100), nullable=False),
    sa.Column('about', sa.NVARCHAR(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('candidate_skill',
    sa.Column('id', sa.SMALLINT(), nullable=False),
    sa.Column('candidate_id', sa.SMALLINT(), nullable=False),
    sa.Column('name', sa.NVARCHAR(length=50), nullable=False),
    sa.Column('level', sa.SMALLINT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('candidate_skill')
    op.drop_table('candidate_info')
    op.drop_table('candidate_experience')
    op.drop_table('candidate_education')
    # ### end Alembic commands ###
